### ISSUE TITLE
wormhole exchange future-compatibility ideas

### ISSUE THREAD

**Issue by warner** [gridsync/gridsync#42]
@meejah and I were talking at this week's Tahoe devchat about a future "tahoe invite/accept" CLI command. It might look awfully similar to the current gridsync invitation, plus some future Accounting identifiers. To enable a native Tahoe client (non-GUI, not wrapped by GridSync) to interoperate with the same provider, it would be great if you could use the same invitation for either form.

I think we can accomplish this by having the two sides of the invitation exchange some version data before sending anything else. That way, the "server" (the side that manages the grid and is extending the invitation) can offer something different, depending upon whether the "client" knows how to do it or not.

I'm thinking the "client" should send a message with just `{abilities: {"client-v1": {}}}`, and the server should send `{abilities: {"server-v1": {}}}`. Both messages would be sent as soon as the wormhole connects, without waiting for anything else. *Then*, if the server sees client-v1, it sends the current gridsync data.

That way, a future server can send something different to a client-v2. Or the client can see "server-v1" and then pretend to be something different.

If it doesn't see that, then this is a client from the future and maybe we emit an error message or something.

Maybe "client-v1" should be spelled "gridsync-v1", etc.

Also, I think our grid-manager design is going to need a message to be passed in each direction (the grid manager sends a pubkey to the client, and the client sends a pubkey to the manager). So the gridsync invitation protocol could anticipate that, sending an empty message from client to server for now. Maybe both sides should send an ACK after receiving this message. The total protocol would then have three messages in each direction: abilities, data, ack, each crossing its counterpart  on the wire.

**Comment by crwood** [comment]
Hi Brian,

This all sounds great to me. As it stands, I have no particular attachment to the "standard" laid out in [docs/invite.rst](https://github.com/gridsync/gridsync/blob/master/docs/invite.rst) (as nobody is really using it) and would be happy to upgrade the invitation protocol in whatever direction the recent discussions take -- especially if it means being able to mitigate DoS attacks against the wormhole server via some sort of auth-token/PoW scheme in the future.

If the plan to implement proper `tahoe invite`/`tahoe accept` subcommands materializes relatively soon, however, I would probably just opt to have Gridsync wrap over those subprocesses (as it currently does with, e.g., `tahoe create-client`, `tahoe start`, etc.) instead of reimplementing it myself. I know @meejah has already done [some work](https://github.com/meejah/lafs) towards this end.

In any case, maybe we should all chat about it more next week at the usual time (if no other topics are on the table) and/or possibly work towards drafting or sketching up a more formal spec/protocol?

**Comment by meejah** [comment]
We should leave the client/server strings generic, IMO: there's nothing gridsync specific about this (and indeed we'd LIKE more people to integrate in this way).

For example, gridsync itself *could* just shell out to `tahoe invite` to do its side (although doing the wormhole stuff "itself" I think makes sense in gridsync's case since it's already using Twisted and can then provide better/more-fine-grained feedback via the UI).

The only remaining tweak here (besides some squashing and depending on a wormhole release with the new API) would be I think deciding on the APPID and relay-URI to burn into `tahoe` -- we'd talked about putting this at e.g. `wormhole.tahoe-lafs.org`. https://LeastAuthority.com is fine to volunteer to continue to run a wormhole server so this would be a Simple Matter of DNS (right, @exarkun?)

**Comment by crwood** [comment]
Closing this as Gridsync 0.3 has since been released (and is compatible with the `tahoe invite` "protocol").
