### ISSUE TITLE
Always asked to "connect"

### ISSUE THREAD

**Issue by meejah** [gridsync/gridsync#614]
When using the Private-Storage branded release of Gridsync I always see the "Connect to PrivateStorage" dialog even though I have storage-time and am connected to https://private.storage 

Below are the the two dialogs I see.

This is on `gnome Full GNOME Desktop Environment, with 1:43+1` according to `aptitude` on debian bookworm.

![both-dialogs](https://user-images.githubusercontent.com/145599/226702987-fa4ad7ec-aec3-450c-a339-990e8272afdc.png)

**Comment by crwood** [comment]
After trying to reproduce this locally, my current/new hypothesis is that you're probably not actually connected to the (current) PrivateStorage production grid since a) upon examining the code, that prompt ("Connect to PrivateStorage") should only appear if you've not already connected to the production grid and b) upon examining your screenshot, I see that you have a batch of 50 GB-months (which is what PS gives per "purchase" event on staging; on production/live you would get 30 GB-months).

Can you please confirm that you're actually connected to the _production_ grid (represented throughout the UI and configs as "PrivateStorage") and not _staging_ ("PrivateStorage Staging")? The grid name should appear in the bottom left of the status panel (where "Syncing" is presently in your screenshot above) -- e.g., in the form "Connected to PrivateStorage" or "Connected to PrivateStorage Staging". Alternatively, you could check the contents of the application config dir (`~/.config/privatestorage`) for a subdirectory with either of those two names; the prompt should no longer appear if you have properly configured tahoe nodedir under `~/.config/privatestorage/PrivateStorage`.
