### ISSUE TITLE
Invite errors could be presented better

### ISSUE THREAD

**Issue by meejah** [gridsync/gridsync#663]
Currently, the UI presents any errors from the invite API with an error-message about an exception, a POST and a 400 response, which is too technical for most users. The actual JSON returned by magic-folder _is_ included in there in the end, but it's probably more useful to the user to extract the `"reason"` field from this and present (only) that.

For example, `There was an error inviting device "foo": <the `reason` field from the error-response>`.

**Comment by crwood** [comment]
Fixed by #664:

* Language in the form of "An exception was raised..." is now "An error occurred...".
* For Magic-Folder errors that provide a `reason` field, the provided `reason` value will be now take priority and be displayed in place of the previously-shown technical information (about, e.g., which HTTP method was used, the status code, etc. for Magic-Folder web API errors).
* Full tracebacks (containing the information previously shown above) are now available via the "Show details..." button.
