### ISSUE TITLE
Accepting a Provider invite with the "Add Folder" UI results in a hung dialog

### ISSUE THREAD

**Issue by exarkun** [gridsync/gridsync#67]
I did this by accident, not realizing I was entering my invitation into the wrong place.

I got a dialog with a progress bar that made it most of the way to the end (but not all the way) and said "Done!" underneath and then hung there until I closed the window.

**Comment by crwood** [comment]
Thanks for reporting this.

From the sounds of it, the progress indicator would have appeared "hung" because, when entering an invite code via the "Add Folder" option (as opposed to adding via the connection pull-down/combo-box), the invite receiver is expecting to perform an additional "step" (namely of joining a magic-folder). In the case of a "provider-only" invite, however, no extra step would be performed (since no magic-folder code would actually be present in the JSON blob).. I'll fix this soon by ensuring that the number of expected steps reflected by UI actually matches the number of operations to be performed by the underlying setup process (i.e., by reading the JSON blob received through the wormhole and actually counting the number of folder invites present -- if any -- instead of just assuming that one would be given).
