### ISSUE TITLE
Size overflow?

### ISSUE THREAD

**Issue by yegortimoshenko** [gridsync/gridsync#78]
I'm using v0.3.1. I've started Gridsync (in debug mode) and after a while size has become negative:

![screenshot_2018-04-09_06-09-43](https://user-images.githubusercontent.com/1643293/38481958-cb3d0e2a-3bbc-11e8-89cc-0ee8e72d0302.png)

Unfortunately, when that happened, there has been nothing out of the ordinary in the logs (only another `add_updated_file` entry), but I can send GPG-encrypted logs on demand.

**Comment by yegortimoshenko** [comment]
I've uploaded another file and now it shows 830 KB, while it has uploaded at least 2GB:

![screenshot_2018-04-09_06-39-42](https://user-images.githubusercontent.com/1643293/38483177-911ed6ce-3bc1-11e8-9c28-f837d08c6ee4.png)

This persists between restarts.

**Comment by yegortimoshenko** [comment]
This happened again:

![screenshot_2018-04-09_11-33-46](https://user-images.githubusercontent.com/1643293/38495682-02f564ca-3bea-11e8-86a0-5ad0d9faaf26.png)

When that happens, it starts upload all over again (judging by debugging logs).

**Comment by crwood** [comment]
Hi Yegor,

Thank you for catching/reporting this!

This _shouldn't_ happen with pure python3 `int`s but, alas, as it turns out, it looks like PyQt's Signals/Slots are actually using C++ types under the hood, accounting for the overflow in the UI..

Anyway, I just pushed [PR 79](https://github.com/gridsync/gridsync/pull/79) which fixes the issue on my end (and which I will merge as soon as CI passes..). You can expect a new release within the next couple of weeks but, in the meantime, I'd welcome you to build/install from source if you'd like or need the fix sooner.

Thanks again for the report!

**Comment by yegortimoshenko** [comment]
Thank you! :-)
